name: 'Setup openpilot Environment (Native)'
description: 'Sets up the openpilot CI environment on a native runner with aggressive caching for apt and pip.'

# Accept the 'is_retried' input from the wrapper action to prevent parsing errors.
inputs:
  is_retried:
    description: 'Input from retry wrapper, not used in this action.'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Set system locale
      shell: bash
      run: |
        sudo sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
        sudo locale-gen

    - name: Cache and install apt packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: >-
          build-essential
          portaudio19-dev
          libasound-dev
          python3-crcmod
          sudo tzdata locales ssh pulseaudio xvfb x11-xserver-utils
          gnome-screenshot python3-tk python3-dev
        # Increment version to force a cache refresh that includes the new packages
        version: 1.4

    - name: Set up Python and cache pip dependencies
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: |
          **/pyproject.toml
          **/requirements*.txt

    - name: Install Python dependencies
      shell: bash
      run: |
        # The crcmod package build emits a deprecation warning which fails the build
        # because PYTHONWARNINGS=error is set globally. We temporarily ignore it for this command.
        PYTHONWARNINGS=ignore::DeprecationWarning python -m pip install .
      env:
        PYTHONUNBUFFERED: "1"
